---
  title: "Salud y enfermedades relacionadas con la dieta"
author:
  - Oier Zuñiga
- Diego Ramirez
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output:
  html_document:
  toc: true
---
## ¿De que trata el informe?
  
  La obesidad es un problema de salud pública que ha alcanzado proporciones epidémicas en todo el mundo. Este informe se centra en explorar la relación entre la obesidad y la salud, así como en analizar datos relevantes.
  
## Algunos datos que hemos obtendio y sus bases de datos de origen

  Este primer excel proviene de la base de datos del govierno datos.gob, en este podemos ver la relación entre la diabetes y la mortalidad que esta provoca.
  Aqui dejamos el url para que podais comprobarlo si quereis;
  https://datos.gob.es/es/catalogo/a16003011-tasa-de-mortalidad-atribuida-a-la-diabetes-por-territorio-historico-y-sexo-indicadores-de-la-agenda-2030-c-a-de-euskadi1

library(readxl)
datos_diabetes <- read_excel("diabetes.xlsx")
head(datos_diabetes) 

  Aqui importamos otro excel, este con datos de la obsidad en la poblacion por sexo;

datos_obesidad <- read_excel("obesidad.xlsx")

head(datos_obesidad)

## Aqui otros links que tienen datos sobre el tema de la salud y la dieta que todavia no hemos podido investigar

https://catalog.data.gov/dataset/?q=hypertension&sort=views_recent+desc&res_format=CSV&ext_location=&ext_bbox=&ext_prev_extent=&tags=hypertension

https://www.niddk.nih.gov/

https://www.niddk.nih.gov/

https://www.data.gov/

https://www.opendatasoft.com/

